language: node_js

sudo: required

before_install:
  - npm i -g npm@5.6.0

notifications:
  email:
    recipients:
      - a.redonda89@gmail.com
      - gil.maricruz@gmail.com
    on_success: always # default: change
on_failure: always # default: always
