language: node_js

sudo: required

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build

notifications:
  email:
    recipients:
      - a.redonda89@gmail.com
      - gil.maricruz@gmail.com
    on_success: always # default: change
on_failure: always # default: always
