language: node_js
    node_js:
    - '4.2|'
sudo: required

notifications:
  email:
    recipients:
      - a.redonda89@gmail.com
      - gil.maricruz@gmail.com
    on_success: always # default: change
on_failure: always # default: always
